[hooks]
enter = "mise i -q && uv sync"

[tools]
ruff = "latest"
uv = "latest"
python = "3.13"

[tasks]
lint = "ruff format . && ruff check ."
test = "uv run pytest"

[tasks.debug]
description = ""
usage = '''
arg "<type>" help="Program to debug (creds or hosts)" default="creds" { choices "creds" "hosts" }
'''

run = '''
echo "[*] Please run the 'poetry run textual console -x EVENT -x DEBUG -x SYSTEM' command"

if [[ ${usage_type?} = "creds" ]]; then
    uv run textual run --dev exegol-history.py set creds
else
    uv run textual run --dev exegol-history.py set hosts
fi
'''
