# Main entrypoint workflow
# This workflow orchestrates all checks and tests by calling the individual workflows
# in the appropriate order. It serves as the single entry point for CI/CD.

name: Checks and tests
# Trigger the workflow on push and pull request events
on: [push, pull_request]

# Concurrency configuration to prevent multiple workflow runs
# from executing simultaneously and to cancel any in-progress runs
concurrency:
  # Define a concurrency group for all workflow runs
  group: nightly_builds
  # Cancel any in-progress workflow runs in the same concurrency group
  cancel-in-progress: true

jobs:
  # Code quality checks (linting, formatting, etc.)
  quality:
    name: Code Quality Checks
    uses: ./.github/workflows/sub_lint.yml

  # Main test suite execution
  testing:
    name: Main Testing
    uses: ./.github/workflows/sub_test.yml