# Main testing workflow for Python 3.13
# This workflow runs the complete test suite on the latest Python version
# to ensure the core functionality works as expected.

name: Main Tests
on:
  workflow_call: # Allows this workflow to be called by other workflows

jobs:
  main-test:
    name: Main Tests (Python 3.13)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      
      - name: Install core dependencies
        run: |
          python -m pip install --upgrade pip
          pipx install poetry
      
      - name: Install project dependencies
        run: poetry install --with dev
      
      - name: Run tests
        run: poetry run pytest -v 