# Code quality workflow
# This workflow runs various code quality checks including
# formatting and linting to ensure code style consistency.

name: Code Quality
on:
  workflow_call: # Allows this workflow to be called by other workflows

jobs:
  lint:
    name: Formatting & Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      
      - name: Install linting dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      
      - name: Run Ruff formatter
        run: ruff format --check .
      
      - name: Run Ruff linter
        run: ruff check --output-format=github . 