# Cross-platform and Python version compatibility testing
# This workflow verifies the project's functionality across different
# Python versions and operating systems by executing a comprehensive
# test suite on each combination.

name: Compatibility & Testing
on:
  workflow_call: # Enables this workflow to be triggered by other workflows

jobs:
  compatibility-tests:
    name: Compatibility & Testing Suite
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Initialize core dependencies
        run: |
          python -m pip install --upgrade pip
          pipx install poetry
      
      - name: Initialize project dependencies
        run: poetry install --with dev
      
      - name: Execute comprehensive tests
        run: poetry run pytest -v 